version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ai_worker_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: ai_tasks
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ai_worker_network

  minio:
    image: minio/minio:latest
    container_name: ai_worker_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - ai_worker_network

  redis:
    image: redis:7.2-alpine
    container_name: ai_worker_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - ai_worker_network

  # Optional: Flower for Celery monitoring
  flower:
    image: mher/flower:latest
    container_name: ai_worker_flower
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: redis://:redis123@redis:6379/0
      FLOWER_PORT: 5555
    depends_on:
      - redis
    networks:
      - ai_worker_network

volumes:
  mongodb_data:
  minio_data:
  redis_data:

networks:
  ai_worker_network:
    driver: bridge